services:
    # 1. Serviço da Aplicação (Laravel com PHP 8.4)
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel12_app_php84
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - "8000:8000"
        command: "php artisan serve --host=0.0.0.0 --port=8000"
        networks:
            - laravel
        depends_on:
            - db

    # 2. Serviço do Banco de Dados (PostgreSQL 17)
    db:
        image: postgres:17
        container_name: laravel12_postgres17_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./docker/data/postgres:/var/lib/postgresql/data
        ports:
            - "${DB_PORT}:5432"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
